=== 9eck0/IFT3225-TP1/Partie 2/bibliotheque.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT bibliotheque (livres, auteurs)>



<!ELEMENT livres (livre*)>
<!ELEMENT livre (titre, annee, prix, couverture, commentaire)>
<!ATTLIST livre
    langue CDATA #REQUIRED
    auteurs IDREF #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT prix (#PCDATA)>
<!ELEMENT couverture (#PCDATA)>



<!ELEMENT auteurs (auteur*)>
<!ELEMENT auteur (((nom, prenom)|(prenom, nom)), pays, commentaire?, photo)>
<!ATTLIST auteur
    ident ID #REQUIRED>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT pays (#PCDATA)>
<!ELEMENT photo (#PCDATA)>    <!-- Pas de support regex dans DTD -->

<!-- commentaire est une restriction commune entre livre et auteur -->
<!ELEMENT commentaire (#PCDATA)>

=== 9eck0/IFT3225-TP1/Partie 2/bibliotheque.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Schéma DTD -->
<!DOCTYPE bibliotheque SYSTEM "bibliotheque.dtd">

<!-- Schéma RelaxNG Compact -->
<?oxygen RNGSchema="bibliotheque.rnc" type="compact"?>

<!-- Feuille de transformation XSLT -->
<?xml-stylesheet type="text/xsl" href="bibliotheque-visualisation.xsl"?>

<!-- Élément racine, schéma XSD -->
<bibliotheque xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bibliotheque.xsd">
    <livres>
        <!-- 1er exemple de livre: tous les éléments & attributs -->
        <livre langue="en-CA" auteurs="auteur1">
            <titre>Livre 1</titre>
            <annee>2000</annee>
            <prix devise="CAD">14.99</prix>
            <couverture>https://www.google.ca/</couverture>
            <commentaire>Résumé du livre 1.</commentaire>
        </livre>
        <!-- 2e exemple de livre: minimum nécessaire d'éléments & attributs -->
        <livre langue="fr-FR" auteurs="auteur1 auteur2">
            <titre>Exemplaire gratuit</titre>
            <annee>1999</annee>
            <prix>0</prix>
        </livre>
    </livres>
    <auteurs>
        <!-- 1er exemple de livre: tous les éléments & attributs -->
        <auteur ident="auteur1">
            <nom>Tremblay</nom>
            <prenom>Alice</prenom>
            <pays>Canada</pays>
            <commentaire>Auteur exclusif de Livre 1.</commentaire>
            <photo>https://www.google.ca/</photo>
        </auteur>
        <!-- 2e exemple de livre: minimum nécessaire d'éléments & attributs -->
        <auteur ident="auteur2">
            <prenom>Bob</prenom>
            <nom>Dupont</nom>
            <pays>France</pays>
            <photo>https://www.google.ca/</photo>
        </auteur>
    </auteurs>
</bibliotheque>
